# Site settings
title: CAY-IT
description: since 2023
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. httpgrace a://command.Z3R0.com.br

# User settings
username: CAY IT

user_description: Nous sommes une entreprise qui crée des sites Web basés sur le design, la modernité et la cybersécurité. Nos projets ne sont pas terminés avant d'être vérifiés et qu'ils respectent les trois piliers
user_title: Full-Stack, Cybersecurité et Reseau & Telecom
email: command.z3r0@gmail.com
# twitter_username: command.Z3R0
github_username: command-Z3R0   
instagram_username:  command.z3r0

exclude: ['package.json', 'src' , 'node_modules']
